name: Windows RDP with Telebit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Enable RDP & Set Password
      run: |
        net user runneradmin ${{ secrets.RDP_PASSWORD }}
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 1
        Write-Output "✅ RDP Enabled"

    - name: Download Telebit
      run: |
        Invoke-WebRequest -Uri "https://raw.githubusercontent.com/telebit/telebit-relay/master/telebit.ps1" -OutFile "telebit.ps1"

    - name: Start Telebit Tunnel
      run: |
        $maxAttempts = 5
        $attempt = 1
        $tunnelUrl = ""

        while ($attempt -le $maxAttempts -and [string]::IsNullOrEmpty($tunnelUrl)) {
          Write-Output "🔄 Attempt $attempt of $maxAttempts to start Telebit tunnel..."

          # Start tunnel as background job
          $tbJob = Start-Job -ScriptBlock { & powershell -ExecutionPolicy Bypass -File "telebit.ps1" quick 3389 }
          Start-Sleep -Seconds 15

          # Try to grab public URL from logs
          $log = Receive-Job $tbJob -Keep
          if ($log -match "tcp://[^\s]+") {
            $tunnelUrl = ($log | Select-String -Pattern "tcp://[^\s]+").Matches.Value
            Write-Output "✅ Tunnel started: $tunnelUrl"
          } else {
            Write-Output "⚠️ Failed on attempt $attempt, retrying..."
            Stop-Job -Name $tbJob.Name -ErrorAction SilentlyContinue
            Remove-Job -Name $tbJob.Name -ErrorAction SilentlyContinue
            Start-Sleep -Seconds 10
          }

          $attempt++
        }

        if ([string]::IsNullOrEmpty($tunnelUrl)) {
          Write-Error "❌ Failed to obtain Telebit public address."
          exit 1
        }

        Write-Output "======================================"
        Write-Output " 🔑 RDP Credentials:"
        Write-Output "   • IP/Host : $tunnelUrl"
        Write-Output "   • User    : runneradmin"
        Write-Output "   • Pass    : ${{ secrets.RDP_PASSWORD }}"
        Write-Output "======================================"
