name: RDP - public host + creds

on:
  workflow_dispatch:

jobs:
  rdp-print-creds:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:
      - name: Validate secret
        shell: pwsh
        env:
          RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
        run: |
          if (-not $env:RDP_PASSWORD) { Write-Error "Please add secret RDP_PASSWORD in repo Settings > Secrets"; exit 1 }
          Write-Host "RDP_PASSWORD present."

      - name: Enable Remote Desktop & Firewall
        shell: pwsh
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name 'UserAuthentication' -Value 0 -Force
          netsh advfirewall firewall add rule name="Allow RDP (cloudflared)" dir=in action=allow protocol=TCP localport=3389
          Restart-Service -Name TermService -Force

      - name: Create local RDP user (password from secret)
        shell: pwsh
        env:
          RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
        run: |
          $username = "rdpuser"
          $pwd = $env:RDP_PASSWORD
          $secure = ConvertTo-SecureString $pwd -AsPlainText -Force
          if (-not (Get-LocalUser -Name $username -ErrorAction SilentlyContinue)) {
            New-LocalUser -Name $username -Password $secure -AccountNeverExpires -PasswordNeverExpires
            Write-Host "User created: $username"
          } else {
            $u = Get-LocalUser -Name $username
            $u | Set-LocalUser -Password $secure
            Write-Host "User exists, password updated"
          }
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username -ErrorAction SilentlyContinue

      - name: Get public IP (if any)
        shell: pwsh
        run: |
          $pub = ""
          try { $pub = (Invoke-RestMethod -Uri "https://api.ipify.org?format=text" -UseBasicParsing -ErrorAction Stop).Trim() } catch {}
          echo "PUBLIC_IP=$pub" >> $env:GITHUB_ENV

      - name: Download cloudflared
        shell: pwsh
        run: |
          $dir = "C:\cloudflared"
          if (-not (Test-Path $dir)) { New-Item -Path $dir -ItemType Directory | Out-Null }
          $exe = Join-Path $dir "cloudflared.exe"
          Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile $exe -UseBasicParsing
          icacls $exe /grant "Users:(RX)" | Out-Null
          echo "CLOUDFLARED_EXE=$exe" >> $env:GITHUB_ENV

      - name: Start ephemeral cloudflared tunnel and capture public host:port
        shell: pwsh
        env:
          RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
        run: |
          $exe = $env:CLOUDFLARED_EXE
          if (-not (Test-Path $exe)) { Write-Error "cloudflared not found at $exe"; exit 1 }
          $log = "C:\cloudflared\cloudflared.log"
          if (Test-Path $log) { Remove-Item $log -Force }
          Start-Job -ScriptBlock {
            & "C:\cloudflared\cloudflared.exe" tunnel --url "tcp://localhost:3389" *>&1 | Out-File -FilePath "C:\cloudflared\cloudflared.log" -Encoding UTF8
          } | Out-Null

          $public = $null
          for ($i=0; $i -lt 60 -and -not $public; $i++) {
            Start-Sleep -Seconds 2
            if (Test-Path $log) {
              $txt = Get-Content $log -Raw -ErrorAction SilentlyContinue
              if ($txt -match "([a-z0-9\-]+\.trycloudflare\.com[:]\d+)") {
                $public = $matches[1]; break
              } elseif ($txt -match "Forwarding.*tcp://([^ \r\n]+)") {
                $public = $matches[1]; break
              }
            }
          }

          if (-not $public) {
            Write-Host "===== cloudflared log (tail 200) ====="
            if (Test-Path $log) { Get-Content $log -Tail 200 } else { Write-Host "(no cloudflared log)"; }
            Write-Error "Failed to obtain cloudflared public address."
            exit 1
          }

          echo "CLOUDFLARE_PUBLIC=$public" >> $env:GITHUB_ENV
          Write-Host "Found public host: $public"

      - name: Final output (prints username/password + host/ip)
        shell: pwsh
        env:
          CLOUDFLARE_PUBLIC: ${{ env.CLOUDFLARE_PUBLIC }}
          PUBLIC_IP: ${{ env.PUBLIC_IP }}
          RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
        run: |
          Write-Host ""
          Write-Host "=== COPY THESE LINES (FINAL) ==="
          Write-Host "PUBLIC_RDP=$env:CLOUDFLARE_PUBLIC"
          Write-Host "PUBLIC_IP=$env:PUBLIC_IP"
          Write-Host "USERNAME=rdpuser"
          Write-Host "PASSWORD=$env:RDP_PASSWORD"
          Write-Host "=== END ==="
