name: Windows RDP with Telebit (Auto-Retry)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Set password
      run: |
        net user runneradmin ${{ secrets.RDP_PASS }}

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Install Telebit
      shell: pwsh
      run: |
        npm install -g telebit@latest

    - name: Start Telebit TCP tunnel with Auto-Retry
      shell: pwsh
      run: |
        $maxAttempts = 5
        $attempt = 1
        $public = $null
        $log = "C:\telebit.log"

        while (-not $public -and $attempt -le $maxAttempts) {
          Write-Host "🔄 Attempt $attempt of $maxAttempts to start Telebit tunnel..."
          if (Test-Path $log) { Remove-Item $log -Force }

          Start-Job -Name tbJob -ScriptBlock {
            & telebit tcp 3389 *>&1 | Out-File -FilePath "C:\telebit.log" -Encoding UTF8
          } | Out-Null

          $elapsed = 0
          while (-not $public -and $elapsed -lt 60) {
            Start-Sleep -Seconds 3
            $elapsed += 3
            if (Test-Path $log) {
              $txt = Get-Content $log -Raw -ErrorAction SilentlyContinue
              if ($txt -match "tcp://([\w\.\-]+:\d+)") { $public = $matches[1]; break }
              if ($txt -match "forwarding.*?([\w\.\-]+\.telebit\.cloud[:]\d+)") { $public = $matches[1]; break }
              if ($txt -match "Forwarding.*?([\w\.\-]+\.telebit\.cloud)") { $public = "$($matches[1]):3389"; break }
            }
          }

          if (-not $public) {
            Write-Host "⚠️ Failed on attempt $attempt, retrying..."
            Stop-Job -Name tbJob -Force -ErrorAction SilentlyContinue
          }
          $attempt++
        }

        if (-not $public) {
          Write-Error "❌ Failed to obtain Telebit public address after $maxAttempts attempts."
          exit 1
        }

        Write-Host "======================================"
        Write-Host "✅ RDP Server is ready!"
        Write-Host "👉 Host: $public"
        Write-Host "👉 User: runneradmin"
        Write-Host "👉 Pass: ${{ secrets.RDP_PASS }}"
        Write-Host "======================================"
